package com.ludex.mobile;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import org.json.*;

public final class LudexDb extends SQLiteOpenHelper {
    public LudexDb(Context c){ super(c,"ludex-mobile.db",null,3); }
    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE games(id TEXT PRIMARY KEY,title TEXT NOT NULL,platform TEXT NOT NULL DEFAULT 'Android',source TEXT NOT NULL DEFAULT 'android',package_name TEXT UNIQUE,installed INTEGER NOT NULL DEFAULT 1,favorite INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Quero jogar',updated_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE play_sessions(id TEXT PRIMARY KEY,game_id TEXT NOT NULL,package_name TEXT,started_at INTEGER NOT NULL,ended_at INTEGER NOT NULL,duration_seconds INTEGER NOT NULL,device TEXT NOT NULL DEFAULT 'android',provider TEXT NOT NULL DEFAULT 'android')");
        db.execSQL("CREATE INDEX idx_sessions_game ON play_sessions(game_id,started_at)");
        db.execSQL("CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)");
    }
    @Override public void onUpgrade(SQLiteDatabase db,int oldV,int newV){if(oldV<2)db.execSQL("CREATE INDEX IF NOT EXISTS idx_sessions_game ON play_sessions(game_id,started_at)");if(oldV<3)db.execSQL("UPDATE games SET updated_at=strftime('%s','now')*1000 WHERE updated_at=0");}
    public String upsertGame(String pkg,String title,boolean installed){String id="android:"+pkg;ContentValues v=new ContentValues();v.put("id",id);v.put("title",title);v.put("package_name",pkg);v.put("installed",installed?1:0);v.put("updated_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("games",null,v,SQLiteDatabase.CONFLICT_IGNORE);ContentValues u=new ContentValues();u.put("title",title);u.put("installed",installed?1:0);u.put("updated_at",System.currentTimeMillis());getWritableDatabase().update("games",u,"id=?",new String[]{id});return id;}
    public void markAllAndroidUninstalled(){ContentValues v=new ContentValues();v.put("installed",0);getWritableDatabase().update("games",v,"source='android'",null);}
    public void insertSession(String id,String game,String pkg,long start,long end){if(end<=start)return;ContentValues v=new ContentValues();v.put("id",id);v.put("game_id",game);v.put("package_name",pkg);v.put("started_at",start);v.put("ended_at",end);v.put("duration_seconds",Math.max(0,(end-start)/1000));getWritableDatabase().insertWithOnConflict("play_sessions",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    public long playtime(String game){try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(duration_seconds),0) FROM play_sessions WHERE game_id=?",new String[]{game})){return c.moveToFirst()?c.getLong(0):0;}}
    public long totalPlaytime(){try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(duration_seconds),0) FROM play_sessions",null)){return c.moveToFirst()?c.getLong(0):0;}}
    public int gameCount(){try(Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM games",null)){return c.moveToFirst()?c.getInt(0):0;}}
    public long getCursor(){try(Cursor c=getReadableDatabase().rawQuery("SELECT value FROM settings WHERE key='usage.cursor'",null)){return c.moveToFirst()?Long.parseLong(c.getString(0)):Math.max(0,System.currentTimeMillis()-86400000L);}}
    public void setCursor(long value){ContentValues v=new ContentValues();v.put("key","usage.cursor");v.put("value",Long.toString(value));getWritableDatabase().insertWithOnConflict("settings",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public JSONArray gamesJson() throws JSONException {JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,title,platform,source,package_name,installed,favorite,status,updated_at FROM games",null)){while(c.moveToNext()){JSONObject o=new JSONObject();o.put("id",c.getString(0));o.put("title",c.getString(1));o.put("platform",c.getString(2));o.put("source",c.getString(3));o.put("package_name",c.getString(4));o.put("installed",c.getInt(5));o.put("favorite",c.getInt(6));o.put("status",c.getString(7));o.put("updated_at_ms",c.getLong(8));a.put(o);}}return a;}
    public JSONArray sessionsJson() throws JSONException {JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,game_id,package_name,started_at,ended_at,duration_seconds,device,provider FROM play_sessions",null)){while(c.moveToNext()){JSONObject o=new JSONObject();o.put("id",c.getString(0));o.put("game_id",c.getString(1));o.put("package_name",c.getString(2));o.put("started_at_ms",c.getLong(3));o.put("ended_at_ms",c.getLong(4));o.put("duration_seconds",c.getLong(5));o.put("device",c.getString(6));o.put("provider",c.getString(7));a.put(o);}}return a;}
    public void importBundle(JSONObject root) throws JSONException {JSONArray gs=root.optJSONArray("games");if(gs!=null)for(int i=0;i<gs.length();i++){JSONObject g=gs.getJSONObject(i);String id=g.optString("id");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("title",g.optString("title","Unknown"));v.put("platform",g.optString("platform","PC"));v.put("source",g.optString("source","sync"));if(g.has("package_name"))v.put("package_name",g.optString("package_name",null));v.put("installed",g.optInt("installed",0));v.put("favorite",g.optInt("favorite",0));v.put("status",g.optString("status","Quero jogar"));v.put("updated_at",g.optLong("updated_at_ms",System.currentTimeMillis()));getWritableDatabase().insertWithOnConflict("games",null,v,SQLiteDatabase.CONFLICT_IGNORE);}JSONArray ss=root.optJSONArray("sessions");if(ss!=null)for(int i=0;i<ss.length();i++){JSONObject s=ss.getJSONObject(i);String id=s.optString("id");if(id.isEmpty())continue;long start=s.optLong("started_at_ms"),end=s.optLong("ended_at_ms");if(start>0&&end>=start)insertSession(id,s.optString("game_id"),s.optString("package_name",null),start,end);}}
}
